apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentaflow-api
  labels:
    app: dentaflow-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dentaflow-api
  template:
    metadata:
      labels:
        app: dentaflow-api
    spec:
      containers:
      - name: dentaflow-api
        image: dentaflow/api:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: stripe-secret-key
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: stripe-publishable-key
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: smtp-host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: smtp-port
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: smtp-pass
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: dentaflow-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: dentaflow-uploads-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: dentaflow-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dentaflow-api-service
spec:
  selector:
    app: dentaflow-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dentaflow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.dentaflow.com
    secretName: dentaflow-tls
  rules:
  - host: api.dentaflow.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dentaflow-api-service
            port:
              number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dentaflow-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dentaflow-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: dentaflow-secrets
type: Opaque
data:
  mongodb-uri: <base64-encoded-mongodb-uri>
  jwt-secret: <base64-encoded-jwt-secret>
  stripe-secret-key: <base64-encoded-stripe-secret-key>
  stripe-publishable-key: <base64-encoded-stripe-publishable-key>
  smtp-host: <base64-encoded-smtp-host>
  smtp-port: <base64-encoded-smtp-port>
  smtp-user: <base64-encoded-smtp-user>
  smtp-pass: <base64-encoded-smtp-pass>
  sentry-dsn: <base64-encoded-sentry-dsn> 